#ifndef FUCK_HELIUM_SRC_VERSION_H_
#define FUCK_HELIUM_SRC_VERSION_H_

#ifndef FUCK_HELIUM_VERSION_MAJOR
#define FUCK_HELIUM_VERSION_MAJOR 0
#endif
#ifndef FUCK_HELIUM_VERSION_MINOR
#define FUCK_HELIUM_VERSION_MINOR 1
#endif
#ifndef FUCK_HELIUM_VERSION_PATCH
#define FUCK_HELIUM_VERSION_PATCH 0
#endif
#ifndef FUCK_HELIUM_VERSION_STRING
#define FUCK_HELIUM_VERSION_STRING "0.1.0"
#endif

#endif  // FUCK_HELIUM_SRC_VERSION_H_
