#ifndef FUCK_HELIUM_SRC_VERSION_H_
#define FUCK_HELIUM_SRC_VERSION_H_

#define FUCK_HELIUM_VERSION_MAJOR 0
#define FUCK_HELIUM_VERSION_MINOR 1
#define FUCK_HELIUM_VERSION_PATCH 0
#define FUCK_HELIUM_VERSION_STRING "0.1.0"

#endif  // FUCK_HELIUM_SRC_VERSION_H_

